"""commented out dueDate

Revision ID: 4a1b4fad9047
Revises: 07ae75ff72d7
Create Date: 2021-09-04 15:19:53.688535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1b4fad9047'
down_revision = '07ae75ff72d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dueDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dueDate', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
