"""added image column to artistTypes

Revision ID: a9d6e834a698
Revises: 385e23bf06be
Create Date: 2021-08-29 11:54:17.649455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d6e834a698'
down_revision = '385e23bf06be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artistTypes', sa.Column('image', sa.String(length=2000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artistTypes', 'image')
    # ### end Alembic commands ###
