"""dueDate back in

Revision ID: afe27bc956b0
Revises: 4a1b4fad9047
Create Date: 2021-09-04 15:24:01.337894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe27bc956b0'
down_revision = '4a1b4fad9047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dueDate', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dueDate')
    # ### end Alembic commands ###
