"""removed inbox table

Revision ID: b14e594f1ebd
Revises: da251ea39b49
Create Date: 2021-09-02 11:31:57.898614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14e594f1ebd'
down_revision = 'da251ea39b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inboxes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inboxes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('newMessages', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='inboxes_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='inboxes_pkey')
    )
    # ### end Alembic commands ###
