"""added numCompletedJobs to Users

Revision ID: d33d367bf09b
Revises: a9d6e834a698
Create Date: 2021-08-29 14:31:53.756256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33d367bf09b'
down_revision = 'a9d6e834a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('numCompletedJobs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'numCompletedJobs')
    # ### end Alembic commands ###
